### ISSUE TITLE
Add some Linux-libre distributions

### ISSUE THREAD

**Issue by Nidrop** [muellermartin/nosystemd.org#12]
How about some distros approved by FSF?
I see the Guix, but u haven't listed others.
[Hyperbola](https://www.hyperbola.info/) uses openrc
[Dragora](https://dragora.org/en/index.html) according wikipedia uses runit

not sure about adding [Parabola](https://www.parabola.nu/), it has two versions: with systemd and with openrc

**Comment by muellermartin** [comment]
Thanks for these great suggestions! I didn't know these distributions. If you provide a PR, I will happily add them to the website!

Regarding Parabola: I think it is okay to add it, if it gives an easy choice to use it without systemd. In the end, it's about the freedom to choose and there the coice is easy.

**Comment by muellermartin** [comment]
Thanks to @Menelkir these distros have been added in PR #17. Therefore I consider this issue as fixed.
