### ISSUE TITLE
Ataraxia Linux is not no systemd distro.

### ISSUE THREAD

**Issue by Zaryob** [muellermartin/nosystemd.org#25]
I wanna report it. Ataraxia linux switched to systemd service manager with latest version. you can check it out from their github group.

bests regards

**Comment by Zaryob** [comment]
https://github.com/ataraxialinux/ataraxia/releases/tag/200913

**Comment by psposito** [comment]
Well done!

It also has to be removed from https://nosystemd.org/

Regards
