### ISSUE TITLE
Adding S6 and Hummingbird to the list?

### ISSUE THREAD

**Issue by 6r1d** [muellermartin/nosystemd.org#32]
Hello. I'd like to know what people here think about:

* [S6](https://skarnet.org/software/s6/) ([The s6 supervision suite A modern alternative to systemd](https://www.youtube.com/watch?v=gZqIEstv5lM)) by @skarnet
* Hummingbird ([GitHub repo](https://github.com/Sweets/hummingbird)) by @Sweets

Maybe it's a good time to add both to the list of init systems?

**Comment by appetrosyan** [comment]
I second both.

**Comment by muellermartin** [comment]
S6 was added in PR #31 and I added Hummingbird in d3fe26e. Thanks for the suggestions.
