### ISSUE TITLE
we need a nosystemd discord server 

### ISSUE THREAD

**Issue by sebaju** [muellermartin/nosystemd.org#33]
I think it would help bring the community together :)

**Comment by Obazzi** [comment]
Discord is a garbage [proprietary](https://stallman.org/discord.html) [spyware](https://spyware.neocities.org/articles/discord.html) that does not [respect the user freedom](https://temora.neocities.org/sentropy/sentropy.html). We should absolutely not have an official Discord server. If you are okay with using Discord but complain about systemd, you need your priorities checked.

I have noting against having an [IRC channel](https://en.wikipedia.org/wiki/Internet_Relay_Chat) or an [XMPP MUC](https://en.wikipedia.org/wiki/XMPP#Multi-user_chat). It would be a really great idea, and I agree that it would help bring the community together. :)

There is also [Matrix](https://matrix.org/), but the Matrix protocol is like the XMPP protocol but if it was bloated and monolithic (like systemd is!). It also takes huge amount of system resources if you try to run your own Matrix server compared to running your own XMPP server. It would be hypocritical to use it while we complain about how systemd is bloated and bad, but it would still be miles better than the proprietary spyware that is Discord.

**Comment by Nidrop** [comment]
I just want to mention these two interesting projects here:
[Revolt](https://github.com/revoltchat) (in beta) - communication platform aimed at creating an open analogue of the proprietary Discord messenger, allowing you to run your own server instance.
[Fosscord](https://github.com/fosscord) (experimental) - free open source selfhostable discord compatible chat, voice and video platform.
