### ISSUE TITLE
[enhancement] Obarun build concept

### ISSUE THREAD

**Issue by Obarun** [muellermartin/nosystemd.org#4]
Hi there,

Can you consider to add obarun.org web page?
Arch based systemd with s6 and s6-rc handled by 66 as replacement of systemd.
https://skarnet.org/software/ 
https://framagit.org/Obarun/66
https://web.obarun.org

Have a good day :).

Eric Vidal

**Comment by muellermartin** [comment]
Hi Eric, currently there is some room left in the list of distros, so I see no reason why to not include it there.

Do you have a logo which I can use to link to the distros website? And which link target do you prefer? https://web.obarun.org/

**Comment by Obarun** [comment]
You can find the graphics part here http://web.obarun.org/obgraphics/
The https://web.obarun.org as main link is ok for me.

Thanks to accept it

**Comment by muellermartin** [comment]
Thanks for the link to the graphics. I've created a smaller version of the logo and added it to the list of distros and linked it to the Oberun website.

You're welcome :)
