### ISSUE TITLE
Add Ataraxia Linux

### ISSUE THREAD

**Issue by protonesso** [muellermartin/nosystemd.org#6]
Hi, I'm developer of Ataraxia Linux. I share your opinion about systemd. I made this distro 3 years ago (started in December 2016). I didn't include systemd because it requires lots of patches and dependencies. I use Busybox init + Busybox runit. I made GNOME desktop working without libsystemd.

Web page: https://ataraxialinux.github.io
Logo: https://avatars0.githubusercontent.com/u/49410282?s=200&v=4

**Comment by muellermartin** [comment]
Thanks for your Linux distro and the suggestion to add it to the list. I've added it in 2b3e853 to the website and the changes should be live.

**Comment by Zaryob** [comment]
ağa beee
